import type { ManagementReportResult, ManagementReportingRow } from "./types";

export type ReportExportMetadata = {
  reportId: string;
  generatedAt: string;
  generatedBy: string;
};

function csvCell(value: string | number | null | undefined): string {
  const text = value == null ? "" : String(value);
  if (/[",\r\n]/.test(text)) return `"${text.replace(/"/g, '""')}"`;
  return text;
}

function tsvCell(value: string | number | null | undefined): string {
  return (value == null ? "" : String(value)).replace(/[\t\r\n]+/g, " ");
}

function exportRows(report: ManagementReportResult): ManagementReportingRow[] {
  return report.rows.map((row) => ({ ...row }));
}

export function serializeReportCsv(
  report: ManagementReportResult,
  metadata: ReportExportMetadata,
): string {
  const lines: string[] = [
    `Report ID,${csvCell(metadata.reportId)}`,
    `Report title,${csvCell(report.title)}`,
    `Generated at,${csvCell(metadata.generatedAt)}`,
    `Generated by,${csvCell(metadata.generatedBy)}`,
    `Record count,${report.recordCount}`,
    `Total claims,${report.totals.totalClaims}`,
    `Approved claims,${report.totals.approvedClaims}`,
    `Declined claims,${report.totals.declinedClaims}`,
    `Pending claims,${report.totals.pendingClaims}`,
    `Average turnaround days,${report.totals.averageTurnaroundDays}`,
    `Illustrative payment amount PGK,${report.totals.illustrativePaymentAmountPgk}`,
    `Disclosure,${csvCell(report.disclosure)}`,
    "",
    "Reference,Worker,Employer,Province,Status,Received",
  ];

  for (const row of exportRows(report)) {
    lines.push(
      [
        row.reference,
        row.workerName,
        row.employerName,
        row.province,
        row.status,
        row.receivedAt.slice(0, 10),
      ]
        .map(csvCell)
        .join(","),
    );
  }

  return `${lines.join("\n")}\n`;
}

export function serializeReportSpreadsheet(
  report: ManagementReportResult,
  metadata: ReportExportMetadata,
): string {
  const lines: string[] = [
    `Report ID\t${tsvCell(metadata.reportId)}`,
    `Report title\t${tsvCell(report.title)}`,
    `Generated at\t${tsvCell(metadata.generatedAt)}`,
    `Generated by\t${tsvCell(metadata.generatedBy)}`,
    `Record count\t${report.recordCount}`,
    `Total claims\t${report.totals.totalClaims}`,
    `Approved claims\t${report.totals.approvedClaims}`,
    `Declined claims\t${report.totals.declinedClaims}`,
    `Pending claims\t${report.totals.pendingClaims}`,
    `Average turnaround days\t${report.totals.averageTurnaroundDays}`,
    `Illustrative payment amount PGK\t${report.totals.illustrativePaymentAmountPgk}`,
    `Disclosure\t${tsvCell(report.disclosure)}`,
    "",
    "Reference\tWorker\tEmployer\tProvince\tStatus\tReceived",
  ];

  for (const row of exportRows(report)) {
    lines.push(
      [
        row.reference,
        row.workerName,
        row.employerName,
        row.province,
        row.status,
        row.receivedAt.slice(0, 10),
      ]
        .map(tsvCell)
        .join("\t"),
    );
  }

  return `${lines.join("\n")}\n`;
}
