-- Persistent, synthetic demonstration data for the Office of Workers Compensation.
-- Each external institution is represented by a private PostgreSQL schema. The
-- browser never receives table privileges; server code uses the public RPCs below.

create extension if not exists pgcrypto;

create schema if not exists owc_core;
create schema if not exists nid_registry;
create schema if not exists ipa_registry;
create schema if not exists irc_registry;
create schema if not exists health_registry;
create schema if not exists insurance_registry;
create schema if not exists employment_registry;
create schema if not exists banking_registry;
create schema if not exists integration_hub;
create schema if not exists audit;
create schema if not exists reporting;

create table if not exists owc_core.scenarios (
  scenario_id text primary key,
  title text not null,
  narrative text not null,
  expected_outcome text not null,
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists owc_core.claimants (
  claimant_id text primary key,
  scenario_id text not null references owc_core.scenarios(scenario_id),
  nid text not null unique,
  full_name text not null,
  phone text,
  email text,
  province text,
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now()
);

create table if not exists owc_core.employers (
  employer_id text primary key,
  registration_no text not null unique,
  legal_name text not null,
  tin text not null,
  policy_no text not null,
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now()
);

create table if not exists owc_core.claims (
  claim_id text primary key,
  scenario_id text not null references owc_core.scenarios(scenario_id),
  claim_reference text not null unique,
  claimant_id text not null references owc_core.claimants(claimant_id),
  employer_id text not null references owc_core.employers(employer_id),
  employee_no text not null,
  medical_certificate_no text,
  account_reference text,
  incident_date date not null,
  incident_type text not null,
  incident_description text not null,
  status text not null,
  amount_pgk numeric(14,2) not null default 0 check (amount_pgk >= 0),
  simulation boolean not null default true check (simulation = true),
  submitted_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists owc_core.claim_status_history (
  history_id bigint generated by default as identity primary key,
  claim_id text not null references owc_core.claims(claim_id),
  status text not null,
  note text not null,
  occurred_at timestamptz not null default now(),
  simulation boolean not null default true check (simulation = true),
  unique (claim_id, status, occurred_at)
);

create table if not exists owc_core.communications (
  communication_id uuid primary key default gen_random_uuid(),
  claim_reference text,
  channel text not null check (channel in ('email', 'sms', 'in_app')),
  recipient text not null,
  event_name text not null,
  message text not null,
  delivery_reference text not null unique,
  delivery_status text not null default 'ACCEPTED',
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now()
);

create table if not exists owc_core.compensation_records (
  compensation_id text primary key,
  claim_reference text not null unique,
  benefit_type text not null,
  approved_amount_pgk numeric(14,2) not null check (approved_amount_pgk >= 0),
  payment_status text not null,
  payment_reference text,
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now()
);

create table if not exists nid_registry.persons (
  nid text primary key,
  first_name text not null,
  surname text not null,
  date_of_birth date not null,
  province text not null,
  identity_status text not null,
  scenario_id text not null,
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now()
);

create table if not exists ipa_registry.companies (
  registration_no text primary key,
  legal_name text not null,
  trading_name text not null,
  status text not null,
  industry text not null,
  registered_address text not null,
  scenario_id text not null,
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now()
);

create table if not exists irc_registry.taxpayers (
  tin text primary key,
  registration_no text not null,
  taxpayer_name text not null,
  status text not null,
  scenario_id text not null,
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now()
);

create table if not exists health_registry.facilities (
  facility_id text primary key,
  facility_name text not null,
  province text not null,
  status text not null default 'ACTIVE',
  simulation boolean not null default true check (simulation = true)
);

create table if not exists health_registry.practitioners (
  practitioner_id text primary key,
  practitioner_name text not null,
  facility_id text not null references health_registry.facilities(facility_id),
  status text not null default 'ACTIVE',
  simulation boolean not null default true check (simulation = true)
);

create table if not exists health_registry.medical_certificates (
  certificate_no text primary key,
  patient_nid text not null,
  facility_id text not null references health_registry.facilities(facility_id),
  practitioner_id text not null references health_registry.practitioners(practitioner_id),
  injury_category text not null,
  incapacity_days integer not null check (incapacity_days >= 0),
  issued_at date not null,
  status text not null,
  scenario_id text not null,
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now()
);

create table if not exists insurance_registry.insurers (
  insurer_id text primary key,
  insurer_name text not null,
  status text not null default 'ACTIVE',
  simulation boolean not null default true check (simulation = true)
);

create table if not exists insurance_registry.policies (
  policy_no text primary key,
  employer_registration_no text not null,
  insurer_id text not null references insurance_registry.insurers(insurer_id),
  cover_type text not null,
  effective_date date not null,
  expiry_date date not null,
  status text not null,
  scenario_id text not null,
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now()
);

create table if not exists employment_registry.employers (
  registration_no text primary key,
  legal_name text not null,
  status text not null,
  simulation boolean not null default true check (simulation = true)
);

create table if not exists employment_registry.employees (
  employee_no text primary key,
  nid text not null,
  employer_registration_no text not null references employment_registry.employers(registration_no),
  employee_name text not null,
  position text not null,
  work_location text not null,
  fortnightly_salary_pgk numeric(12,2) not null check (fortnightly_salary_pgk >= 0),
  employment_status text not null,
  scenario_id text not null,
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now()
);

create table if not exists employment_registry.wage_snapshots (
  snapshot_id text primary key,
  employee_no text not null references employment_registry.employees(employee_no),
  pay_period_end date not null,
  gross_pay_pgk numeric(12,2) not null check (gross_pay_pgk >= 0),
  ordinary_hours numeric(8,2) not null check (ordinary_hours >= 0),
  simulation boolean not null default true check (simulation = true)
);

create table if not exists banking_registry.banks (
  bank_id text primary key,
  bank_name text not null,
  status text not null default 'ACTIVE',
  simulation boolean not null default true check (simulation = true)
);

create table if not exists banking_registry.accounts (
  account_reference text primary key,
  bank_id text not null references banking_registry.banks(bank_id),
  account_name text not null,
  masked_account_number text not null,
  owner_nid text not null,
  status text not null,
  scenario_id text not null,
  simulation boolean not null default true check (simulation = true),
  created_at timestamptz not null default now()
);

create table if not exists banking_registry.simulated_transactions (
  transaction_id uuid primary key default gen_random_uuid(),
  idempotency_key text not null unique,
  transaction_reference text not null unique,
  receipt_reference text not null unique,
  claim_reference text not null,
  account_reference text not null references banking_registry.accounts(account_reference),
  amount_pgk numeric(14,2) not null check (amount_pgk > 0),
  currency text not null default 'PGK' check (currency = 'PGK'),
  status text not null default 'SIMULATED' check (status = 'SIMULATED'),
  simulation boolean not null default true check (simulation = true),
  money_movement boolean not null default false check (money_movement = false),
  generated_at timestamptz not null default now()
);

create table if not exists integration_hub.service_state (
  service text primary key,
  mode text not null default 'online' check (mode in ('online', 'offline', 'degraded')),
  latency_ms integer not null default 0 check (latency_ms >= 0),
  message text,
  updated_at timestamptz not null default now()
);

create table if not exists integration_hub.events (
  event_id bigint generated by default as identity primary key,
  correlation_id text not null,
  service text not null,
  operation text not null,
  status text not null,
  duration_ms integer not null default 0 check (duration_ms >= 0),
  source text not null default 'persistent_demo',
  scenario_id text,
  occurred_at timestamptz not null default now()
);

create index if not exists integration_events_occurred_at_idx
  on integration_hub.events (occurred_at desc);

create table if not exists integration_hub.verification_results (
  verification_id uuid primary key default gen_random_uuid(),
  claim_reference text not null,
  service text not null,
  identifier text not null,
  matched boolean not null,
  response jsonb not null,
  verified_at timestamptz not null default now(),
  unique (claim_reference, service, identifier)
);

create table if not exists audit.events (
  audit_id bigint generated by default as identity primary key,
  actor text not null default 'owc_demo_server',
  action text not null,
  entity_type text not null,
  entity_reference text,
  metadata jsonb not null default '{}'::jsonb,
  simulation boolean not null default true check (simulation = true),
  occurred_at timestamptz not null default now()
);

create or replace view reporting.claim_overview as
select
  c.claim_reference,
  c.scenario_id,
  cl.full_name as claimant_name,
  e.legal_name as employer_name,
  c.incident_type,
  c.status,
  c.amount_pgk,
  c.submitted_at,
  c.updated_at
from owc_core.claims c
join owc_core.claimants cl on cl.claimant_id = c.claimant_id
join owc_core.employers e on e.employer_id = c.employer_id;

-- Deterministic scenario catalogue. Re-running this migration is safe.
insert into owc_core.scenarios (scenario_id, title, narrative, expected_outcome) values
  ('OWC-S01', 'Approved workplace injury', 'Verified worker with complete evidence and a simulated compensation payment.', 'APPROVED_AND_SIMULATED_PAID'),
  ('OWC-S02', 'Medical evidence follow-up', 'Claim initially lacks medical evidence, then proceeds after verification.', 'APPROVED_AFTER_INFORMATION_REQUEST'),
  ('OWC-S03', 'Identity mismatch decline', 'Submitted identity details do not match the authoritative demonstration record.', 'DECLINED_IDENTITY_MISMATCH'),
  ('OWC-S04', 'Fatal incident dependant benefit', 'A dependant receives a simulated death benefit assessment.', 'APPROVED_DEPENDANT_BENEFIT'),
  ('OWC-S05', 'Occupational illness review', 'A long-latency occupational illness is assessed using employment history.', 'UNDER_REVIEW')
on conflict (scenario_id) do update set
  title = excluded.title,
  narrative = excluded.narrative,
  expected_outcome = excluded.expected_outcome,
  updated_at = now();

insert into nid_registry.persons (nid, first_name, surname, date_of_birth, province, identity_status, scenario_id) values
  ('NID-00010001', 'Mara', 'Kila', '1987-04-18', 'National Capital District', 'VERIFIED', 'OWC-S01'),
  ('NID-00010002', 'Lina', 'Tovue', '1991-08-07', 'Morobe Province', 'VERIFIED', 'OWC-S02'),
  ('NID-00010003', 'Karo', 'Mena', '1984-02-22', 'Eastern Highlands Province', 'REVIEW', 'OWC-S03'),
  ('NID-00010004', 'Talia', 'Aru', '1979-11-05', 'Central Province', 'VERIFIED', 'OWC-S04'),
  ('NID-00010005', 'Pita', 'Wama', '1965-06-13', 'Western Province', 'VERIFIED', 'OWC-S05')
on conflict (nid) do update set identity_status = excluded.identity_status, scenario_id = excluded.scenario_id;

insert into ipa_registry.companies (registration_no, legal_name, trading_name, status, industry, registered_address, scenario_id) values
  ('IPA-2020-1001', 'Pacific Engineering Ltd', 'Pacific Engineering', 'ACTIVE', 'Engineering Services', 'Waigani Industrial Area, Port Moresby', 'OWC-S01'),
  ('IPA-2018-2044', 'Highlands Construction Services Ltd', 'Highlands Construction', 'ACTIVE', 'Civil Construction', 'Lae, Morobe Province', 'OWC-S02'),
  ('IPA-2019-3003', 'Goroka Freight Ltd', 'Goroka Freight', 'ACTIVE', 'Transport and Logistics', 'Goroka, Eastern Highlands Province', 'OWC-S03'),
  ('IPA-2016-4004', 'Central Forestry Operations Ltd', 'Central Forestry', 'ACTIVE', 'Forestry', 'Kupiano, Central Province', 'OWC-S04'),
  ('IPA-1998-5005', 'Fly River Minerals Ltd', 'Fly River Minerals', 'ACTIVE', 'Mining', 'Kiunga, Western Province', 'OWC-S05')
on conflict (registration_no) do update set status = excluded.status, scenario_id = excluded.scenario_id;

insert into irc_registry.taxpayers (tin, registration_no, taxpayer_name, status, scenario_id) values
  ('TIN-90010001', 'IPA-2020-1001', 'Pacific Engineering Ltd', 'COMPLIANT', 'OWC-S01'),
  ('TIN-90010002', 'IPA-2018-2044', 'Highlands Construction Services Ltd', 'COMPLIANT', 'OWC-S02'),
  ('TIN-90010003', 'IPA-2019-3003', 'Goroka Freight Ltd', 'COMPLIANT', 'OWC-S03'),
  ('TIN-90010004', 'IPA-2016-4004', 'Central Forestry Operations Ltd', 'REVIEW', 'OWC-S04'),
  ('TIN-90010005', 'IPA-1998-5005', 'Fly River Minerals Ltd', 'COMPLIANT', 'OWC-S05')
on conflict (tin) do update set status = excluded.status, scenario_id = excluded.scenario_id;

insert into health_registry.facilities (facility_id, facility_name, province) values
  ('FAC-01', 'National Workplace Medical Centre', 'National Capital District'),
  ('FAC-02', 'Morobe Occupational Health Clinic', 'Morobe Province'),
  ('FAC-03', 'Goroka Provincial Hospital', 'Eastern Highlands Province'),
  ('FAC-04', 'Central Provincial Hospital', 'Central Province'),
  ('FAC-05', 'Tabubil Occupational Health Service', 'Western Province')
on conflict (facility_id) do update set facility_name = excluded.facility_name;

insert into health_registry.practitioners (practitioner_id, practitioner_name, facility_id) values
  ('PRAC-01', 'Dr Aro Kila', 'FAC-01'),
  ('PRAC-02', 'Dr Lina Balo', 'FAC-02'),
  ('PRAC-03', 'Dr Walo Kora', 'FAC-03'),
  ('PRAC-04', 'Dr Mera Pala', 'FAC-04'),
  ('PRAC-05', 'Dr Sali Wama', 'FAC-05')
on conflict (practitioner_id) do update set practitioner_name = excluded.practitioner_name;

insert into health_registry.medical_certificates
  (certificate_no, patient_nid, facility_id, practitioner_id, injury_category, incapacity_days, issued_at, status, scenario_id) values
  ('MED-2026-00451', 'NID-00010001', 'FAC-01', 'PRAC-01', 'Workplace limb injury', 14, '2026-09-10', 'VALID', 'OWC-S01'),
  ('MED-2026-00452', 'NID-00010002', 'FAC-02', 'PRAC-02', 'Workplace back injury', 10, '2026-09-08', 'VALID', 'OWC-S02'),
  ('MED-2026-00453', 'NID-00010003', 'FAC-03', 'PRAC-03', 'Soft tissue injury', 5, '2026-08-25', 'VALID', 'OWC-S03'),
  ('MED-2026-00454', 'NID-00010004', 'FAC-04', 'PRAC-04', 'Fatal workplace trauma', 0, '2026-07-18', 'VALID', 'OWC-S04'),
  ('MED-2026-00455', 'NID-00010005', 'FAC-05', 'PRAC-05', 'Occupational respiratory illness', 90, '2026-06-30', 'VALID', 'OWC-S05')
on conflict (certificate_no) do update set status = excluded.status, scenario_id = excluded.scenario_id;

insert into insurance_registry.insurers (insurer_id, insurer_name) values
  ('INS-01', 'Workers Mutual Insurance Ltd'),
  ('INS-02', 'Employer Assurance Service'),
  ('INS-03', 'Pacific Workers Underwriters'),
  ('INS-04', 'National General Insurance'),
  ('INS-05', 'Resources Risk Cover Ltd')
on conflict (insurer_id) do update set insurer_name = excluded.insurer_name;

insert into insurance_registry.policies
  (policy_no, employer_registration_no, insurer_id, cover_type, effective_date, expiry_date, status, scenario_id) values
  ('WC-POL-2026-01872', 'IPA-2020-1001', 'INS-01', 'Workers Compensation', '2026-01-01', '2026-12-31', 'ACTIVE', 'OWC-S01'),
  ('WC-POL-2026-01903', 'IPA-2018-2044', 'INS-02', 'Workers Compensation', '2026-04-01', '2027-03-31', 'ACTIVE', 'OWC-S02'),
  ('WC-POL-2026-02011', 'IPA-2019-3003', 'INS-03', 'Workers Compensation', '2026-01-01', '2026-12-31', 'ACTIVE', 'OWC-S03'),
  ('WC-POL-2026-01704', 'IPA-2016-4004', 'INS-04', 'Workers Compensation and Death Benefit', '2026-01-01', '2026-12-31', 'ACTIVE', 'OWC-S04'),
  ('WC-POL-2026-01505', 'IPA-1998-5005', 'INS-05', 'Workers Compensation and Occupational Disease', '2026-01-01', '2026-12-31', 'ACTIVE', 'OWC-S05')
on conflict (policy_no) do update set status = excluded.status, scenario_id = excluded.scenario_id;

insert into employment_registry.employers (registration_no, legal_name, status)
select registration_no, legal_name, status from ipa_registry.companies
on conflict (registration_no) do update set legal_name = excluded.legal_name, status = excluded.status;

insert into employment_registry.employees
  (employee_no, nid, employer_registration_no, employee_name, position, work_location, fortnightly_salary_pgk, employment_status, scenario_id) values
  ('EMP-0001001', 'NID-00010001', 'IPA-2020-1001', 'Mara Kila', 'Heavy Equipment Operator', 'Port Moresby Operations Site', 2400, 'ACTIVE', 'OWC-S01'),
  ('EMP-0001002', 'NID-00010002', 'IPA-2018-2044', 'Lina Tovue', 'Site Administration Officer', 'Lae Project Office', 1850, 'ACTIVE', 'OWC-S02'),
  ('EMP-0001003', 'NID-00010003', 'IPA-2019-3003', 'Karo Mena', 'Truck Driver', 'Goroka Depot', 2100, 'ACTIVE', 'OWC-S03'),
  ('EMP-0001004', 'NID-00010004', 'IPA-2016-4004', 'Talia Aru', 'Forestry Supervisor', 'Kupiano Logging Site', 2750, 'DECEASED', 'OWC-S04'),
  ('EMP-0001005', 'NID-00010005', 'IPA-1998-5005', 'Pita Wama', 'Process Plant Technician', 'Kiunga Operations', 3200, 'RETIRED', 'OWC-S05')
on conflict (employee_no) do update set employment_status = excluded.employment_status, scenario_id = excluded.scenario_id;

insert into employment_registry.wage_snapshots (snapshot_id, employee_no, pay_period_end, gross_pay_pgk, ordinary_hours) values
  ('WAGE-S01', 'EMP-0001001', '2026-09-04', 2400, 80),
  ('WAGE-S02', 'EMP-0001002', '2026-09-04', 1850, 80),
  ('WAGE-S03', 'EMP-0001003', '2026-08-21', 2100, 80),
  ('WAGE-S04', 'EMP-0001004', '2026-07-17', 2750, 80),
  ('WAGE-S05', 'EMP-0001005', '2026-06-19', 3200, 80)
on conflict (snapshot_id) do update set gross_pay_pgk = excluded.gross_pay_pgk;

insert into banking_registry.banks (bank_id, bank_name) values
  ('BANK-01', 'National Commercial Bank'),
  ('BANK-02', 'Banking Service 02'),
  ('BANK-03', 'Highlands Community Bank'),
  ('BANK-04', 'Papua Coastal Bank'),
  ('BANK-05', 'Resources Employees Bank')
on conflict (bank_id) do update set bank_name = excluded.bank_name;

insert into banking_registry.accounts
  (account_reference, bank_id, account_name, masked_account_number, owner_nid, status, scenario_id) values
  ('BANK-ACC-7842', 'BANK-01', 'Mara Kila', '****7842', 'NID-00010001', 'VERIFIED', 'OWC-S01'),
  ('BANK-ACC-3921', 'BANK-02', 'Lina Tovue', '****3921', 'NID-00010002', 'VERIFIED', 'OWC-S02'),
  ('BANK-ACC-5088', 'BANK-03', 'Karo Mena', '****5088', 'NID-00010003', 'REVIEW', 'OWC-S03'),
  ('BANK-ACC-1147', 'BANK-04', 'Talia Aru Estate', '****1147', 'NID-00010004', 'VERIFIED', 'OWC-S04'),
  ('BANK-ACC-6605', 'BANK-05', 'Pita Wama', '****6605', 'NID-00010005', 'VERIFIED', 'OWC-S05')
on conflict (account_reference) do update set status = excluded.status, scenario_id = excluded.scenario_id;

insert into owc_core.claimants (claimant_id, scenario_id, nid, full_name, phone, email, province)
select 'CLMT-' || right(scenario_id, 3), scenario_id, nid, first_name || ' ' || surname,
       '+675 7000 ' || right(nid, 4), lower(first_name || '.' || surname) || '@example.test', province
from nid_registry.persons
on conflict (claimant_id) do update set full_name = excluded.full_name, province = excluded.province;

insert into owc_core.employers (employer_id, registration_no, legal_name, tin, policy_no) values
  ('EMPL-S01', 'IPA-2020-1001', 'Pacific Engineering Ltd', 'TIN-90010001', 'WC-POL-2026-01872'),
  ('EMPL-S02', 'IPA-2018-2044', 'Highlands Construction Services Ltd', 'TIN-90010002', 'WC-POL-2026-01903'),
  ('EMPL-S03', 'IPA-2019-3003', 'Goroka Freight Ltd', 'TIN-90010003', 'WC-POL-2026-02011'),
  ('EMPL-S04', 'IPA-2016-4004', 'Central Forestry Operations Ltd', 'TIN-90010004', 'WC-POL-2026-01704'),
  ('EMPL-S05', 'IPA-1998-5005', 'Fly River Minerals Ltd', 'TIN-90010005', 'WC-POL-2026-01505')
on conflict (employer_id) do update set legal_name = excluded.legal_name, policy_no = excluded.policy_no;

insert into owc_core.claims
  (claim_id, scenario_id, claim_reference, claimant_id, employer_id, employee_no, medical_certificate_no, account_reference,
   incident_date, incident_type, incident_description, status, amount_pgk, submitted_at) values
  ('CLAIM-S01', 'OWC-S01', 'OWC-2026-005112', 'CLMT-S01', 'EMPL-S01', 'EMP-0001001', 'MED-2026-00451', 'BANK-ACC-7842', '2026-09-03', 'INJURY', 'Crush injury while operating workplace equipment.', 'APPROVED', 8400, '2026-09-11T02:00:00Z'),
  ('CLAIM-S02', 'OWC-S02', 'OWC-2026-005113', 'CLMT-S02', 'EMPL-S02', 'EMP-0001002', 'MED-2026-00452', 'BANK-ACC-3921', '2026-09-01', 'INJURY', 'Back injury while moving site records.', 'APPROVED', 4625, '2026-09-05T01:30:00Z'),
  ('CLAIM-S03', 'OWC-S03', 'OWC-2026-005114', 'CLMT-S03', 'EMPL-S03', 'EMP-0001003', 'MED-2026-00453', 'BANK-ACC-5088', '2026-08-20', 'INJURY', 'Loading-area incident with an identity mismatch.', 'DECLINED', 0, '2026-08-26T03:00:00Z'),
  ('CLAIM-S04', 'OWC-S04', 'OWC-2026-005115', 'CLMT-S04', 'EMPL-S04', 'EMP-0001004', 'MED-2026-00454', 'BANK-ACC-1147', '2026-07-18', 'FATALITY', 'Fatal incident during forestry operations.', 'APPROVED', 50000, '2026-07-21T00:30:00Z'),
  ('CLAIM-S05', 'OWC-S05', 'OWC-2026-005116', 'CLMT-S05', 'EMPL-S05', 'EMP-0001005', 'MED-2026-00455', 'BANK-ACC-6605', '2026-06-20', 'OCCUPATIONAL_ILLNESS', 'Respiratory illness linked to long-term workplace exposure.', 'UNDER_REVIEW', 0, '2026-07-01T04:15:00Z')
on conflict (claim_id) do update set status = excluded.status, amount_pgk = excluded.amount_pgk, updated_at = now();

insert into owc_core.claim_status_history (claim_id, status, note, occurred_at) values
  ('CLAIM-S01', 'APPROVED', 'All demonstration verifications completed.', '2026-09-14T02:00:00Z'),
  ('CLAIM-S02', 'INFORMATION_REQUESTED', 'Medical certificate requested.', '2026-09-06T01:30:00Z'),
  ('CLAIM-S02', 'APPROVED', 'Medical evidence received and verified.', '2026-09-12T01:30:00Z'),
  ('CLAIM-S03', 'DECLINED', 'Identity details require correction.', '2026-08-28T03:00:00Z'),
  ('CLAIM-S04', 'APPROVED', 'Dependant benefit assessment completed.', '2026-07-30T00:30:00Z'),
  ('CLAIM-S05', 'UNDER_REVIEW', 'Historical exposure records under review.', '2026-07-03T04:15:00Z')
on conflict (claim_id, status, occurred_at) do update set note = excluded.note;

insert into owc_core.compensation_records
  (compensation_id, claim_reference, benefit_type, approved_amount_pgk, payment_status, payment_reference) values
  ('COMP-S01', 'OWC-2026-005112', 'TEMPORARY_INCAPACITY', 8400, 'SIMULATED_PAID', 'SIM-PAY-SEED-0001'),
  ('COMP-S02', 'OWC-2026-005113', 'TEMPORARY_INCAPACITY', 4625, 'APPROVED', null),
  ('COMP-S04', 'OWC-2026-005115', 'DEPENDANT_DEATH_BENEFIT', 50000, 'APPROVED', null)
on conflict (compensation_id) do update set approved_amount_pgk = excluded.approved_amount_pgk, payment_status = excluded.payment_status;

insert into integration_hub.service_state (service, mode, latency_ms, message) values
  ('nid', 'online', 120, 'Synthetic NID registry available'),
  ('ipa', 'online', 145, 'Synthetic IPA registry available'),
  ('irc', 'online', 165, 'Synthetic IRC registry available'),
  ('employer', 'online', 105, 'Synthetic employment registry available'),
  ('medical', 'online', 180, 'Synthetic health registry available'),
  ('insurance', 'online', 135, 'Synthetic insurance registry available'),
  ('bank', 'online', 150, 'Simulation-only banking registry available'),
  ('notifications', 'online', 90, 'Synthetic notification service available')
on conflict (service) do update set mode = excluded.mode, latency_ms = excluded.latency_ms, message = excluded.message, updated_at = now();

create or replace function public.owc_demo_lookup(p_service text, p_identifier text)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_service text := lower(trim(p_service));
  v_identifier text := upper(trim(p_identifier));
  v_data jsonb;
  v_operation text;
  v_status text := 'success';
  v_correlation text := 'OWC-DEMO-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16));
  v_started timestamptz := clock_timestamp();
  v_mode text;
  v_scenario text;
begin
  select mode into v_mode from integration_hub.service_state where service = v_service;
  if v_mode = 'offline' then
    raise exception 'Demonstration service % is offline', v_service using errcode = 'P0001';
  end if;

  case v_service
    when 'nid' then
      v_operation := 'verify_identity';
      select jsonb_build_object('matched', true, 'nid', nid, 'firstName', first_name, 'surname', surname,
        'dateOfBirth', date_of_birth, 'province', province, 'identityStatus', identity_status), scenario_id
      into v_data, v_scenario from nid_registry.persons where nid = v_identifier and identity_status = 'VERIFIED';
      if v_data is null then v_data := jsonb_build_object('matched', false, 'nid', v_identifier); end if;
    when 'ipa' then
      v_operation := 'verify_company';
      select jsonb_build_object('active', true, 'registrationNo', registration_no, 'legalName', legal_name,
        'tradingName', trading_name, 'industry', industry, 'registeredAddress', registered_address), scenario_id
      into v_data, v_scenario from ipa_registry.companies where registration_no = v_identifier and status = 'ACTIVE';
      if v_data is null then v_data := jsonb_build_object('active', false, 'registrationNo', v_identifier); end if;
    when 'irc' then
      v_operation := 'check_compliance';
      select jsonb_build_object('found', true, 'tin', tin, 'taxpayerName', taxpayer_name,
        'registrationNo', registration_no, 'status', status), scenario_id
      into v_data, v_scenario from irc_registry.taxpayers where tin = v_identifier;
      if v_data is null then v_data := jsonb_build_object('found', false, 'tin', v_identifier, 'status', 'UNKNOWN'); end if;
    when 'employer' then
      v_operation := 'verify_employment';
      select jsonb_build_object('employed', true, 'employeeNo', employee_no, 'nid', nid,
        'employerRegistrationNo', employer_registration_no, 'employeeName', employee_name, 'position', position,
        'workLocation', work_location, 'fortnightlySalaryPgk', fortnightly_salary_pgk,
        'employmentStatus', employment_status), scenario_id
      into v_data, v_scenario from employment_registry.employees where employee_no = v_identifier and employment_status = 'ACTIVE';
      if v_data is null then v_data := jsonb_build_object('employed', false, 'employeeNo', v_identifier); end if;
    when 'medical' then
      v_operation := 'verify_certificate';
      select jsonb_build_object('valid', true, 'certificateNo', m.certificate_no, 'patientNid', m.patient_nid,
        'provider', f.facility_name, 'practitioner', p.practitioner_name, 'injuryCategory', m.injury_category,
        'incapacityDays', m.incapacity_days, 'issuedAt', m.issued_at), m.scenario_id
      into v_data, v_scenario
      from health_registry.medical_certificates m
      join health_registry.facilities f on f.facility_id = m.facility_id
      join health_registry.practitioners p on p.practitioner_id = m.practitioner_id
      where m.certificate_no = v_identifier and m.status = 'VALID';
      if v_data is null then v_data := jsonb_build_object('valid', false, 'certificateNo', v_identifier); end if;
    when 'insurance' then
      v_operation := 'verify_policy';
      select jsonb_build_object('active', true, 'policyNo', p.policy_no,
        'employerRegistrationNo', p.employer_registration_no, 'insurer', i.insurer_name,
        'coverType', p.cover_type, 'expiryDate', p.expiry_date), p.scenario_id
      into v_data, v_scenario from insurance_registry.policies p
      join insurance_registry.insurers i on i.insurer_id = p.insurer_id
      where p.policy_no = v_identifier and p.status = 'ACTIVE';
      if v_data is null then v_data := jsonb_build_object('active', false, 'policyNo', v_identifier); end if;
    when 'bank' then
      v_operation := 'verify_account';
      select jsonb_build_object('verified', true, 'accountReference', a.account_reference,
        'bankName', b.bank_name, 'accountName', a.account_name, 'maskedAccountNumber', a.masked_account_number), a.scenario_id
      into v_data, v_scenario from banking_registry.accounts a
      join banking_registry.banks b on b.bank_id = a.bank_id
      where a.account_reference = v_identifier and a.status = 'VERIFIED';
      if v_data is null then v_data := jsonb_build_object('verified', false, 'accountReference', v_identifier); end if;
    else
      raise exception 'Unknown demonstration service: %', v_service using errcode = '22023';
  end case;

  if coalesce((v_data ->> coalesce(
    case v_service when 'nid' then 'matched' when 'ipa' then 'active' when 'irc' then 'found'
      when 'employer' then 'employed' when 'medical' then 'valid' when 'insurance' then 'active' when 'bank' then 'verified' end,
    'matched'))::boolean, false) = false then
    v_status := 'not_found';
  end if;

  insert into integration_hub.events (correlation_id, service, operation, status, duration_ms, scenario_id)
  values (v_correlation, v_service, v_operation, v_status,
    greatest(0, floor(extract(epoch from (clock_timestamp() - v_started)) * 1000)::integer), v_scenario);

  return jsonb_build_object('source', 'persistent_demo', 'service', v_service, 'operation', v_operation,
    'correlationId', v_correlation, 'timestamp', now(), 'data', v_data);
end;
$$;

create or replace function public.owc_demo_process_payment(
  p_idempotency_key text,
  p_claim_reference text,
  p_account_reference text,
  p_amount_pgk numeric
)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_transaction banking_registry.simulated_transactions%rowtype;
  v_account banking_registry.accounts%rowtype;
  v_bank_name text;
  v_duplicate boolean := false;
  v_sequence text;
  v_correlation text := 'OWC-DEMO-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16));
begin
  if nullif(trim(p_idempotency_key), '') is null then raise exception 'Idempotency key is required' using errcode = '22023'; end if;
  if p_amount_pgk is null or p_amount_pgk <= 0 then raise exception 'Amount must be greater than zero' using errcode = '22023'; end if;

  select * into v_transaction from banking_registry.simulated_transactions where idempotency_key = p_idempotency_key;
  if found then
    v_duplicate := true;
  else
    select * into v_account from banking_registry.accounts
    where account_reference = upper(trim(p_account_reference)) and status = 'VERIFIED';
    if not found then raise exception 'Simulated payment requires a verified demonstration bank account' using errcode = 'P0001'; end if;
    if not exists (select 1 from owc_core.claims where claim_reference = upper(trim(p_claim_reference))) then
      raise exception 'Unknown demonstration claim reference' using errcode = 'P0001';
    end if;

    v_sequence := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
    insert into banking_registry.simulated_transactions
      (idempotency_key, transaction_reference, receipt_reference, claim_reference, account_reference, amount_pgk)
    values
      (p_idempotency_key,
       'SIM-PAY-' || extract(year from now())::integer || '-' || v_sequence,
       'SIM-RCPT-' || extract(year from now())::integer || '-' || v_sequence,
       upper(trim(p_claim_reference)), v_account.account_reference, p_amount_pgk)
    on conflict (idempotency_key) do nothing
    returning * into v_transaction;
    if not found then
      select * into v_transaction from banking_registry.simulated_transactions
      where idempotency_key = p_idempotency_key;
      v_duplicate := true;
    end if;
  end if;

  select * into v_account from banking_registry.accounts
  where account_reference = v_transaction.account_reference;
  select b.bank_name into v_bank_name from banking_registry.accounts a
  join banking_registry.banks b on b.bank_id = a.bank_id
  where a.account_reference = v_transaction.account_reference;

  insert into integration_hub.events (correlation_id, service, operation, status, duration_ms)
  values (v_correlation, 'bank', 'process_payment', 'success', 0);
  insert into audit.events (action, entity_type, entity_reference, metadata)
  values ('SIMULATED_PAYMENT', 'claim', v_transaction.claim_reference,
    jsonb_build_object('transactionReference', v_transaction.transaction_reference, 'moneyMovement', false));

  return jsonb_build_object('source', 'persistent_demo', 'service', 'bank', 'operation', 'process_payment',
    'correlationId', v_correlation, 'timestamp', now(), 'data', jsonb_build_object(
      'transactionReference', v_transaction.transaction_reference, 'receiptReference', v_transaction.receipt_reference,
      'status', v_transaction.status, 'simulation', v_transaction.simulation, 'moneyMovement', v_transaction.money_movement,
      'currency', v_transaction.currency, 'generatedAt', v_transaction.generated_at,
      'claimReference', v_transaction.claim_reference, 'accountReference', v_transaction.account_reference,
      'bankName', v_bank_name, 'accountName', v_account.account_name,
      'maskedAccountNumber', v_account.masked_account_number, 'amountPgk', v_transaction.amount_pgk,
      'duplicateRequest', v_duplicate));
end;
$$;

create or replace function public.owc_demo_list_events(p_limit integer default 100)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, public
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', e.event_id, 'correlationId', e.correlation_id, 'service', e.service,
    'operation', e.operation, 'status', e.status, 'durationMs', e.duration_ms,
    'source', e.source, 'scenarioId', e.scenario_id, 'timestamp', e.occurred_at
  ) order by e.occurred_at desc), '[]'::jsonb)
  from (select * from integration_hub.events order by occurred_at desc limit greatest(1, least(coalesce(p_limit, 100), 500))) e;
$$;

create or replace function public.owc_demo_list_service_state()
returns jsonb
language sql
security invoker
set search_path = pg_catalog, public
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'service', service, 'mode', mode, 'latencyMs', latency_ms, 'message', message, 'updatedAt', updated_at
  ) order by service), '[]'::jsonb)
  from integration_hub.service_state;
$$;

create or replace function public.owc_demo_send_notification(
  p_channel text,
  p_recipient text,
  p_event text,
  p_message text,
  p_claim_reference text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_delivery text := 'MSG-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16));
  v_correlation text := 'OWC-DEMO-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16));
begin
  if p_channel not in ('email', 'sms', 'in_app') then raise exception 'Unsupported notification channel' using errcode = '22023'; end if;
  insert into owc_core.communications
    (claim_reference, channel, recipient, event_name, message, delivery_reference)
  values (p_claim_reference, p_channel, p_recipient, p_event, p_message, v_delivery);
  insert into integration_hub.events (correlation_id, service, operation, status, duration_ms)
  values (v_correlation, 'notifications', 'send_notification', 'success', 0);
  return jsonb_build_object('source', 'persistent_demo', 'service', 'notifications', 'operation', 'send_notification',
    'correlationId', v_correlation, 'timestamp', now(), 'data', jsonb_build_object(
      'accepted', true, 'deliveryReference', v_delivery, 'channel', p_channel,
      'recipient', p_recipient, 'event', p_event, 'message', p_message));
end;
$$;

-- Private buckets only: public, false. Access is intentionally server-side.
insert into storage.buckets (id, name, public) values
  ('owc-claim-evidence', 'owc-claim-evidence', false),
  ('owc-identity-documents', 'owc-identity-documents', false),
  ('owc-medical-certificates', 'owc-medical-certificates', false),
  ('owc-employment-documents', 'owc-employment-documents', false),
  ('owc-insurance-documents', 'owc-insurance-documents', false),
  ('owc-simulated-receipts', 'owc-simulated-receipts', false)
on conflict (id) do update set public = false;

revoke all on schema owc_core, nid_registry, ipa_registry, irc_registry, health_registry,
  insurance_registry, employment_registry, banking_registry, integration_hub, audit, reporting from public, anon, authenticated;
revoke all on all tables in schema owc_core, nid_registry, ipa_registry, irc_registry, health_registry,
  insurance_registry, employment_registry, banking_registry, integration_hub, audit, reporting from public, anon, authenticated;
revoke all on function public.owc_demo_lookup(text, text) from public, anon, authenticated;
revoke all on function public.owc_demo_process_payment(text, text, text, numeric) from public, anon, authenticated;
revoke all on function public.owc_demo_list_events(integer) from public, anon, authenticated;
revoke all on function public.owc_demo_list_service_state() from public, anon, authenticated;
revoke all on function public.owc_demo_send_notification(text, text, text, text, text) from public, anon, authenticated;

grant usage on schema owc_core, nid_registry, ipa_registry, irc_registry, health_registry,
  insurance_registry, employment_registry, banking_registry, integration_hub, audit, reporting to service_role;
grant select, insert, update, delete on all tables in schema owc_core, nid_registry, ipa_registry, irc_registry,
  health_registry, insurance_registry, employment_registry, banking_registry, integration_hub, audit to service_role;
grant select on all tables in schema reporting to service_role;
grant usage, select on all sequences in schema owc_core, integration_hub, audit to service_role;
grant execute on function public.owc_demo_lookup(text, text) to service_role;
grant execute on function public.owc_demo_process_payment(text, text, text, numeric) to service_role;
grant execute on function public.owc_demo_list_events(integer) to service_role;
grant execute on function public.owc_demo_list_service_state() to service_role;
grant execute on function public.owc_demo_send_notification(text, text, text, text, text) to service_role;
